<template>
    <div>
        <el-container>
            <el-header>
            <h2>客服名单</h2>                          
            </el-header>
            <el-main>
                <el-table
                :data="this.$store.state.SData_Company[0].service"
            >
                <el-table-column
                prop="id"
                label="客服ID"
                width="100">
                </el-table-column>
                <el-table-column
                prop="name"
                label="客服昵称"
                width="130">
                </el-table-column>
                <el-table-column
                prop="tName"
                label="客服姓名"
                width="130">
                </el-table-column>
                <el-table-column
                prop="account"
                label="客服账户"
                width="150">
                </el-table-column>
                <el-table-column
                prop="pwd"
                label="客服密码"
                width="150">
                </el-table-column>
                <el-table-column
                prop="tel"
                label="客服电话"
                width="150">
                </el-table-column>
                <el-table-column
                prop="email"
                label="客服邮箱"
                width="200">
                </el-table-column>
                </el-table>
            </el-main>
            <el-footer>
                <div><el-table
                :data="this.$store.state.SData_Company[0].nService"
            >
                <el-table-column
                prop="name"
                label="客服昵称"
                width="130">
                </el-table-column>
                <el-table-column
                prop="tName"
                label="客服姓名"
                width="130">
                </el-table-column>
                <el-table-column
                prop="account"
                label="客服账户"
                width="150">
                </el-table-column>
                <el-table-column
                prop="pwd"
                label="客服密码"
                width="150">
                </el-table-column>
                <el-table-column
                prop="tel"
                label="客服电话"
                width="150">
                </el-table-column>
                <el-table-column
                prop="email"
                label="客服邮箱"
                width="200">
                </el-table-column>
                <el-table-column
                label="操作"
                width="200">
                <template slot-scope="scope">
                <el-button type="success">接受</el-button>
                <el-button type="warning">拒绝</el-button>
                </template>
                </el-table-column>
                </el-table></div>
            </el-footer>
        </el-container>
    </div>
</template>

<script></script>

<style></style>
